CREATE TABLE EMP(
	EMPNO INT NOT NULL PRIMARY KEY,
	ENAME VARCHAR (6) NOT NULL,
	JOB VARCHAR (9) NOT NULL,
	MGR INT,
	HIREDATE DATE NOT NULL,
	SAL INT NOT NULL,
	COMM INT,
	DEPTNO INT NOT NULL FOREIGN KEY REFERENCES DEPT (DEPTNO)
);

CREATE TABLE DEPT(
	DEPTNO INT NOT NULL PRIMARY KEY,
	DNAME VARCHAR(10) NOT NULL,
	LOC VARCHAR(8) NOT NULL
);



