USE db_langage_manipulation_donnees;

DROP TABLE IF EXISTS EMP;

DROP TABLE IF EXISTS DEPT;

CREATE TABLE DEPT(
	DEPTNO INT NOT NULL,
	DNAME VARCHAR(10) NOT NULL,
	LOC VARCHAR(8) NOT NULL,
	CONSTRAINT PK_DEPTNO PRIMARY KEY (DEPTNO)
);

CREATE TABLE EMP(
	EMPNO INT NOT NULL,
	ENAME VARCHAR (6) NOT NULL,
	JOB VARCHAR (9) NOT NULL,
	MGR INT,
	HIREDATE DATE NOT NULL,
	SAL INT NOT NULL,
	COMM INT,
	DEPTNO INT NOT NULL,
	CONSTRAINT PK_EMPNO PRIMARY KEY (EMPNO), 
	CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
	CONSTRAINT FK_MGR FOREIGN KEY (MGR) REFERENCES EMP (EMPNO)	
);

