USE db_langage_manipulation_donnees;


--Q1
SELECT ENAME, JOB, SAL 
FROM EMP
WHERE DEPTNO = 10;


--Q2
SELECT ENAME, JOB, SAL
FROM EMP
WHERE JOB = 'MANAGER' AND SAL > 2800;


--Q3
SELECT ENAME 
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO <> 30;


--Q4
SELECT *
FROM EMP 
WHERE SAL > 1200 AND SAL < 1400;


--Q5
SELECT ENAME 
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 30
ORDER BY ENAME ASC;


--Q6
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30
ORDER BY SAL ASC;


--Q7
SELECT JOB, SAL
FROM EMP
ORDER BY JOB DESC, SAL DESC;


--Q8
SELECT DISTINCT JOB
FROM EMP;


--Q9
SELECT DNAME
FROM DEPT
INNER JOIN EMP 
ON DEPT.DEPTNO = EMP.DEPTNO 
WHERE ENAME = 'ALLEN';


--Q10
SELECT DNAME, ENAME, JOB, SAL
FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO 
ORDER BY DNAME DESC, SAL DESC;


--Q11
SELECT ENAME, SAL, COMM, SAL+COMM
FROM EMP
WHERE JOB = 'SALESMAN'
ORDER BY SAL+COMM DESC;


--Q12
SELECT ENAME, JOB, 
FORMAT(HIREDATE, 'ddd-dd-MMM-yyyy', 'FR-fr') AS HIREDATE 
FROM EMP
WHERE DEPTNO = 20;


--Q13
SELECT MAX(SAL), DEPTNO
FROM EMP 
GROUP BY DEPTNO;


--Q14
SELECT DNAME,DEPT.DEPTNO, JOB, SUM(SAL) AS SALDEPT, COUNT(DISTINCT EMPNO) AS NOMBEMPLOYER, AVG(SAL) AS MOYENNESAL
FROM EMP
FULL JOIN DEPT 
ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME,DEPT.DEPTNO, JOB 
ORDER BY DNAME;


--Q15
SELECT DNAME,DEPT.DEPTNO, JOB, SUM(SAL) AS SALDEPT, COUNT(DISTINCT EMPNO) AS NOMBEMPLOYER, AVG(SAL) AS MOYENNESAL
FROM EMP
FULL JOIN DEPT 
ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME,DEPT.DEPTNO, JOB 
HAVING COUNT(JOB) >= 2
ORDER BY DNAME;


--Q16
SELECT ENAME, DEPTNO, SAL, JOB
FROM EMP
WHERE JOB = (SELECT JOB FROM EMP
where ENAME ='JONES');


--Q17
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (
SELECT AVG(SAL)
FROM EMP
);


--Q18
CREATE TABLE PROJET(
	NUMPROJET SMALLINT NOT NULL,
	NOMPROJET VARCHAR(5) NOT NULL,
	BUDGET INT NOT NULL,
	PRIMARY KEY (NUMPROJET)
);

INSERT INTO PROJET (NUMPROJET, NOMPROJET, BUDGET)
VALUES	(101,	'ALPHA',	96000),
		(102,	'BETA',		82000),
		(103,	'GAMMA',	15000);


--Q19
ALTER TABLE EMP
ADD NUMPROJET SMALLINT;
UPDATE EMP 
SET NUMPROJET = 101
WHERE DEPTNO = 30 ;
UPDATE EMP
SET NUMPROJET = 102
WHERE DEPTNO <> 30;

SELECT * 
FROM EMP;


--Q20
CREATE VIEW EMPOYER_DEBILE 
AS
SELECT ENAME, JOB, DNAME, NOMPROJET 
FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
INNER JOIN PROJET
ON EMP.NUMPROJET = PROJET.NUMPROJET;



--Q21
SELECT *
FROM EMPOYER_DEBILE
ORDER BY DNAME ASC, NOMPROJET ASC;


--Q22
SELECT NOMPROJET, ENAME, JOB
FROM EMPOYER_DEBILE
WHERE JOB = 'MANAGER';


--PARTIE 2


--Q1
SELECT DEPTNO, JOB, ENAME
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO IN (20, 30);